### PR TITLE
made this project actually legal by making a us .z64 sm64 rom needed to extract the data

### PR DESCRIPTION
**Pull request by uuphoria**

### CODE REVIEW

**Comment by uuphoria** [comment]
the delete directorys were for the original folders on the repo that weren't legal

**Comment by uuphoria** [comment]
legal files were kept

**Comment by uuphoria** [comment]
also before accepting this, please use the "README.md" file to learn how to set it up with node.js
Type `npm run build` in the terminal to set it up for the repo

**Comment by uuphoria** [comment]
Guide on build: When it finishes building you'll get a folder named: dist
Use the contents from dist to put on the repo
That's how to setup this request properly

**Comment by NotAn127** [comment]
I will merge it, when it looks good enough, [need the "select file" option] and same layout as mine

**Comment by uuphoria** [comment]
no you have to type npm run build on your pc in the git cloned directory of my fork, it willa ppear in the dist folder you can then put the files inside to the github and serve files from there

**Pull request closed without merging**
